name: update_sub

on:
  push:
    branches: main
    paths:
      - 'src/sub.ts'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      
      - uses: pnpm/action-setup@v3

      - run: pnpm install

      - run: pnpm sub

      - name: Git commit
        run: |
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git config --global core.autocrlf true
          git config --global core.safecrlf false
          git status
          git add .
          git commit -a -m "chore: update sub file"
        continue-on-error: true
